import { Check, Ruler, ShieldCheck, Wind } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

const specs = [["Aplicación", "Terrazas, balcones y quinchos"], ["Configuración", "Paneles de cristal plegables y desplazables"], ["Vidrio", "10 mm o 12 mm, según evaluación técnica"], ["Fabricación", "A medida de cada vano"], ["Instalación", "Sujeta a revisión de superficie y condiciones del proyecto"]];
const highlights = [[Wind, "Protección", "Ayuda a reducir viento, polvo y lluvia."], [Ruler, "A medida", "Diseñado según las dimensiones de tu vano."], [ShieldCheck, "Seguridad", "Vidrio y configuración definidos para el proyecto."], [Check, "Uso simple", "Paneles pensados para un manejo fluido."]] as const;

export default function FichaTecnica() {
  return <><SiteHeader /><PageHero eyebrow="FICHA TÉCNICA" title="Cortinas de cristal plegables." copy="Información referencial para entender el sistema. La configuración final se define tras una evaluación técnica en terreno." /><main className="container py-20"><section className="grid gap-12 lg:grid-cols-[1fr_1fr]"><div className="folding-glass-image min-h-[460px] rounded-tr-[5rem]" /><div><p className="eyebrow">SISTEMA</p><h2 className="display mt-4 text-5xl">Apertura flexible, vista despejada.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Los paneles se desplazan por su guía y se pliegan hacia un costado, permitiendo abrir el espacio cuando lo necesitas y cerrar para protegerlo de las condiciones exteriores.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{highlights.map(([Icon, title, text]) => <div className="border-t border-slate-200 pt-4" key={title}><Icon size={20} className="text-[#278998]" /><h3 className="mt-3 text-sm font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></div></section><section className="mt-24 border-y border-slate-200 py-16"><p className="eyebrow">ESPECIFICACIONES REFERENCIALES</p><div className="mt-7 grid border-l border-t border-slate-200 md:grid-cols-2">{specs.map(([name, value]) => <div className="border-b border-r border-slate-200 p-6" key={name}><p className="text-xs font-bold tracking-widest text-[#278998]">{name}</p><p className="mt-3 text-base leading-7 text-slate-700">{value}</p></div>)}</div></section><section className="mt-16 rounded-[2rem] bg-[#dceff8] p-8 md:p-12"><h2 className="display text-4xl">¿Tu balcón necesita una solución de seguridad?</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">La Ley N.º 21.842 reconoce la instalación de sistemas adicionales, permanentes y resistentes para prevenir caídas accidentales. Revisamos cada caso para proponer una alternativa acorde al espacio, a la instalación y a las exigencias de la comunidad.</p><a className="btn btn-primary mt-7" href="/contacto">Solicitar evaluación</a></section></main><SiteFooter /></>;
}
